apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.applicationName }}
  annotations: {}
spec:
  selector:
    matchLabels:
      app: {{ .Values.applicationName }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.applicationName }}
    spec:
      containers:
        - name: container
          image: >-
            quay.vapo.va.gov/vapo_tst/0001-dapp-tst/frontend:regisapp1.0
          ports:
            - containerPort: 8080
              protocol: TCP
          env: []
      imagePullSecrets: []
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  paused: false