#------ Dynamic Values Added to YAML Files ---------

#-- The Namespace creating the yaml files on
namespace:

#-- The name of the application being deployed that will be applied to all artifacts
applicationName:

imageRepoTag: regisapp1.0
#-- The latest image tag you wish to deploy


#-- The number of pods you wish to have running default is one
replicasNum: 1

imageRepoLocation: 'quay.vapo.va.gov/vapo_tst/0001-dapp-tst/frontend:'