kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Values.applicationName }}
  namespace: {{ .Values.namespace }}  
spec:
  to:
    kind: Service
    name: {{ .Values.applicationName }}
  tls: null
  host: {{ .Values.applicationName }}.apps.vapo-aws-sbx.va.gov
  path: /
  port:
    targetPort: 3000