kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Values.applicationName }} 
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.applicationName }}     
spec:
  to:
    kind: Service
    name: {{ .Values.applicationName }} 
  tls: null
  host: student-registration.apps.vapo-aws-sbx.va.gov
  path: /
  port:
    targetPort: 3000-tcp